# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 162f5cb1f23e99f8e9d86d46d8d1e50142a7720ecf56a140131967776006b5c0187ff50060013886ae96eb56fcea3b7216ed86f8750a44b3b2690e6204238d73

test:
  secret_key_base: a479a489464655258caaf93ac41636e5b771ecf60092b0078aead4694d93912516439d1e97c3fe9b8cb7771b4658d28943faa75c1b80d3b1edd1712cb5e24c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
